default:
  image: circleci/node:12.14

stages:
- install
- tests
- lint

install:
  script: "npm install"
  stage : install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

unit-tests:
  script: "CI=true npm run test"
  stage : tests

lint:
  script: "npm run lint:ci"
  stage : lint
